### ISSUE TITLE
Trying to edit unicode file in wxe.exe but only some glyphs are showing

### ISSUE THREAD

**Issue by arcfide** [sakachin2/XE#5]
I am attempting to edit a UTF-8 file in wxe, but I have trouble with the glyphs showing up. If I manually set the font to the font that has the glyphs I want to use (the Setup GUI will not let me), I can see the glyphs in the file itself, but when attempting to type them in using a Windows IME, most of the time i get a `?`. I am using an IME that requires that I type the characters using a combination of the CTRL key and the key corresponding to the character I want to type. This doesn't appear to work in the text only version, but does sometimes, but not always work in the Windowed version, even though display of the file appears to be fine.

**Comment by arcfide** [comment]
Okay, I have a little better understanding of what is going on here. I've read the UTF8 Support documentation in your help files carefully, and I think I can see what is going on, but I am not sure how to fix it. 

I can type *some* unicode characters, which appear to be recognized immediately. These include `¨×÷¯` and so forth. I think these are showing up because they are considered valid ASCII and are considered okay within the translation table or something. 

I can copy and paste UTF-8 around the interface. I can also use the Hex input mode and type the characters I want. For example, I can type U+237A using the hex input mode and things work fine. The only thing that isn't working is when I try to type the character directly using the IME. When I do that then I get the `?` glyph indicating, according to the documentation, that there was some sort of translation error or an invalid UTF-8 codepoint. This could be, as it is a 3rd party Windows IME, which means that it could be sending something other than UTF-8 (some other Unicode?).

I tried to use the `-Nm` mode to allow for raw input, but that is actually worse. Here, I cannot type even some of the basic characters, and everything comes out wrong. 

However, it appears that the editor can handle these characters, and they display correctly in the file, but I just need some way to input them efficiently, as the hex mode is not efficient. I think that this might be fixed by using some sort of adjustment to the translation tables or the like to accept these characters as valid, but I am not sure how to do this. I tried to look at the INI file for the translation table information, but it is not clear to me how it works. I see the bit-vectors there, but I don't know what they mean or how they work, and I don't know what goes into a sample translation table. 

Any help would be appreciated, as this appears to be the only ISPF/Xedit style editor that actually handles Unicode.

**Comment by RonSMeyer** [comment]
I'm not really familiar with what you're trying to do but from several 
years of working with XE and reading the documentation I know there are 
two options "Ligature" and "Unicomb" that have to do with UTF-8 and how 
they're handled. The bottom-of-panel line displays the current value of 
those options. Have you looked at those options?

**Comment by arcfide** [comment]
Clarifying the issue a little bit, here's what works:

* Opening/editing a Unicode file (I see all the characters correctly)
* Pasting Unicode anywhere in the editor (I see all the characters correctly)
* Entering the hex values for the characters using the Hex Input Mode gives me the correct characters

The one thing that doesn't work is when I attempt to type special characters using a 3rd-party Windows IME. In that case, Some of the characters make it through, but the Unicode ones do not, and show up as `?` characters, which indicates to me that the system considers them invalid codepoints or something like this. I'm trying to figure out how to get XE to recognize these as valid characters to type, instead of just giving me the `?` symbol. 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by sakachin2** [comment]
Please let me know Settings->Clock&Language->Language, 
and 3'rd party IME output(input to wxe).
Check IME output as following.
"eb file1",  "hex", unicode? character input on the text line, check code on the hex line.

**Comment by sakachin2** [comment]
Wxe's bug was found, will be fixed soon in a week.

**Comment by arcfide** [comment]
Great! Do you still need me to follow the instructions outlined above?

**Comment by sakachin2** [comment]
No thank you if your IME is WizKey..I tested using WizKey trial version v1.5.0.8.



     ----- Original Message -----

**Comment by arcfide** [comment]
Thanks! That's not the IME I am using, but it is possible that it is doing a similar thing. Here's the software I am using:

https://www.dyalog.com/download-zone.htm?p=download

The IME on Windows uses the CTRL key and so, typing CTRL+A CTRL+S will give `⍺⌈`. I will be happy to test with the new fixes and help out with additional feedback if the fixes don't work. Thanks!

**Comment by sakachin2** [comment]
v129Q was uploaded.
Please try it.
I tested on Dyalog IME.
""""""""
About /Nm,Ligature etc.
.edit command option CPU8/CPLC:
    e.g. "e file1 CPU8" : open file1 as UTF8 file.
    No need to open at next, specify CPLC to reset CPU8.
.FontCharSet on wxe Setup dialog
    Select codepage to display codepoint if "Default" is not proper.
    Character glyph width depends on the font, you may see small character occupying 2 columns.
    Wxe ligature mode (by Setup diralog or toggle switch by Alt+";") shrinks line according actual glyph size. 
.comman line option /C:  e.g. /C1252
    Codepage used to Unicode-->LocaleCode translation.
    Default is of Windows setting.
    "?" is put when translation error for CPLC file.
    "chcp" command is alternative for xe console version on CommandPrompt.
.commandline option /Nm: 
    Put UTF8 code to CPLC file while keybord mode is UTF8 mode by Alt+u key,
    it is indicated by "===>" is changes to "=u=>".
    Use for the case Unicode-->LocaleCode translation err.
.(E)Disp_tr_tb_wxe settion in ::xe.ini file.
    Display unprintable character by alternative character to avoid screen corrupted.
    Applied to locale codepoint of 0x00-0xff for non UTF8 file and 0x00-0x7f for UTF8 file.
    e.g. (E)Disp_tr_tb_wxe = 80 = 1000000000000001
         0x80 and 0x8f is shown by alternative glyph indicated by (E)Disp_trans_char=FF #(FF)# display char for English  mode un-displayable char. (FF means U-25aa)

**Comment by arcfide** [comment]
Thanks! I'll get to testing this as soon as I can. Likely that will be after the new year given the holiday situations.

**Comment by arcfide** [comment]
I just tested this version and I can confirm that it seems to be working now! Thank you very much. 

どうもありがとうございました。
