### ISSUE TITLE
Problem to implement gxe installation on Ubuntu / Linux 20

### ISSUE THREAD

**Issue by luisgonzalez-moviments-net** [sakachin2/XE#9]
In installation process at configure step:   No package 'libgnomeui-2.0' found
But   libgnomeui   has been deprecated  for  Ubuntu 20
any suggestions to install lovely gxe at ubuntu 20 ?  many thanks

**Comment by RonSMeyer** [comment]
These are the packages I had to pre-install for XE Editor

1. build-essential
2. lib64ncurses-dev:i386
3. libcups2-dev
4. libappstream-glib-dev
5. libdbusmenu-gtk3-dev

When you run configure:

./configure --enable-libgnome2=no

**Comment by luisgonzalez-moviments-net** [comment]
it's works . Thanks
